FROM python:3.10.6-slim

COPY requirements_mlflow.txt /requirements_mlflow.txt
RUN pip install --no-cache-dir -r requirements_mlflow.txt && \
  rm requirements_mlflow.txt

EXPOSE 5001

ENV BACKEND_URI postgresql+psycopg2://postgres:postgres@mlflow_db/mlflow_db
ENV ARTIFACT_LOCATION s3://cycling
ENV MLFLOW_HOST '0.0.0.0'
ENV MLFLOW_PORT 5001
ENV MLFLOW_S3_ENDPOINT_URL http://172.18.0.3:9000
ENV AWS_ACCESS_KEY_ID masoud
ENV AWS_SECRET_ACCESS_KEY "Strong#Pass#2022"
ENV AWS_REGION us-west-1
ENV S3_ENDPOINT_URL http://172.18.0.3:9000

CMD mlflow server --backend-store-uri ${BACKEND_URI} --default-artifact-root ${ARTIFACT_LOCATION} --host ${MLFLOW_HOST} --port ${MLFLOW_PORT} --artifacts-destination ${ARTIFACT_LOCATION} --serve-artifacts 