version: '3'

services:
  mlflow_db:
    image: postgres:13
    container_name: mlflow_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mlflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  minio:
    image: minio/minio
    container_name: minio_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    # volumes:
    #   - minio_data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: $AWS_ACCESS_KEY_ID
      MINIO_ROOT_PASSWORD: $AWS_SECRET_ACCESS_KEY
    command: server --console-address ":9001" /data

  mlflow_server:
    image: 'atcommons/mlflow-server'
    container_name: mlflow_server
    build:
      context: .
      dockerfile: Dockerfile_mlflow
    ports:
      - "5001:5001"
    volumes:
      - "./data:/mlflow"
    env_file:
      - .env
    environment:
      BACKEND_URI: $MLFLOW_TRACKING_URI
      ARTIFACT_LOCATION: $ARTIFACT_LOCATION

volumes:
  postgres_data:
  minio_data: